#pragma once

/**
 * Auto-generated Live2D shader header.
 *
 * All shader sources from the StandardES directories are embedded
 * as static const char* strings for in-memory loading.
 *
 * Do not edit manually -- regenerate with convert_shaders.py.
 */

#include <cstring>

// ============================================================
// Framework Shaders (CubismNativeFramework / StandardES)
// ============================================================

// Source: FragShaderSrc.frag
static const char* g_fragShaderSrc =
    "/**\n"
    " * Copyright(c) Live2D Inc. All rights reserved.\n"
    " *\n"
    " * Use of this source code is governed by the Live2D Open Software license\n"
    " * that can be found at https://www.live2d.com/eula/live2d-open-software-license-agreement_en.html.\n"
    " */\n"
    "\n"
    "#version 100\n"
    "\n"
    "precision highp float;\n"
    "\n"
    "varying vec2 v_texCoord; //v2f.texcoord\n"
    "uniform sampler2D s_texture0; //_MainTex\n"
    "uniform vec4 u_baseColor; //v2f.color\n"
    "uniform vec4 u_multiplyColor;\n"
    "uniform vec4 u_screenColor;\n"
    "\n"
    "void main()\n"
    "{\n"
    "    vec4 texColor = texture2D(s_texture0, v_texCoord);\n"
    "    texColor.rgb = texColor.rgb * u_multiplyColor.rgb;\n"
    "    texColor.rgb = texColor.rgb + u_screenColor.rgb - (texColor.rgb * u_screenColor.rgb);\n"
    "    vec4 color = texColor * u_baseColor;\n"
    "    gl_FragColor = vec4(color.rgb * color.a, color.a);\n"
    "}\n"
    "\n";


// Source: FragShaderSrcAlphaBlend.frag
static const char* g_fragShaderSrcAlphaBlend =
    "/**\n"
    " * Copyright(c) Live2D Inc. All rights reserved.\n"
    " *\n"
    " * Use of this source code is governed by the Live2D Open Software license\n"
    " * that can be found at https://www.live2d.com/eula/live2d-open-software-license-agreement_en.html.\n"
    " */\n"
    "\n"
    "#if !defined CSM_ALPHA_BLEND_MODE\n"
    "#error not define symbol: CSM_ALPHA_BLEND_MODE.\n"
    "\n"
    "#else\n"
    "vec4 OverlapRgba(vec3 color, vec3 colorSource, vec3 colorDestination, vec3 parameter)\n"
    "{\n"
    "    vec3 rgb = color * parameter.x + colorSource * parameter.y + colorDestination * parameter.z;\n"
    "    float alpha = parameter.x + parameter.y + parameter.z;\n"
    "    return vec4(rgb, alpha);\n"
    "}\n"
    "\n"
    "#if CSM_ALPHA_BLEND_MODE == 0 // OVER\n"
    "vec4 AlphaBlend(vec3 color, vec4 colorSource, vec4 colorDestination)\n"
    "{\n"
    "    vec3 parameter = vec3(colorSource.a * colorDestination.a, colorSource.a * (1.0 - colorDestination.a), colorDestination.a * (1.0 - colorSource.a));\n"
    "    return OverlapRgba(color, colorSource.rgb, colorDestination.rgb, parameter);\n"
    "}\n"
    "\n"
    "#elif CSM_ALPHA_BLEND_MODE == 1 // ATOP\n"
    "vec4 AlphaBlend(vec3 color, vec4 colorSource, vec4 colorDestination)\n"
    "{\n"
    "    vec3 parameter = vec3(colorSource.a * colorDestination.a, 0, colorDestination.a * (1.0 - colorSource.a));\n"
    "    return OverlapRgba(color, colorSource.rgb, colorDestination.rgb, parameter);\n"
    "}\n"
    "\n"
    "#elif CSM_ALPHA_BLEND_MODE == 2 // OUT\n"
    "vec4 AlphaBlend(vec3 color, vec4 colorSource, vec4 colorDestination)\n"
    "{\n"
    "    vec3 parameter = vec3(0.0, 0.0, colorDestination.a * (1.0 - colorSource.a));\n"
    "    return OverlapRgba(color, colorSource.rgb, colorDestination.rgb, parameter);\n"
    "}\n"
    "\n"
    "#elif CSM_ALPHA_BLEND_MODE == 3 // CONJOINT OVER\n"
    "vec4 AlphaBlend(vec3 color, vec4 colorSource, vec4 colorDestination)\n"
    "{\n"
    "    vec3 parameter = vec3(min(colorSource.a, colorDestination.a), max(colorSource.a - colorDestination.a, 0.0), max(colorDestination.a - colorSource.a, 0.0));\n"
    "    return OverlapRgba(color, colorSource.rgb, colorDestination.rgb, parameter);\n"
    "}\n"
    "\n"
    "#elif CSM_ALPHA_BLEND_MODE == 4 // DISJOINT OVER\n"
    "vec4 AlphaBlend(vec3 color, vec4 colorSource, vec4 colorDestination)\n"
    "{\n"
    "    vec3 parameter = vec3(max(colorSource.a + colorDestination.a - 1.0, 0.0), min(colorSource.a, 1.0 - colorDestination.a), min(colorDestination.a, 1.0 - colorSource.a));\n"
    "    return OverlapRgba(color, colorSource.rgb, colorDestination.rgb, parameter);\n"
    "}\n"
    "\n"
    "#else\n"
    "#error not supported blend function\n"
    "\n"
    "#endif\n"
    "#endif\n"
    "\n";


// Source: FragShaderSrcBlend.frag
static const char* g_fragShaderSrcBlend =
    "/**\n"
    " * Copyright(c) Live2D Inc. All rights reserved.\n"
    " *\n"
    " * Use of this source code is governed by the Live2D Open Software license\n"
    " * that can be found at https://www.live2d.com/eula/live2d-open-software-license-agreement_en.html.\n"
    " */\n"
    "\n"
    "#version 100\n"
    "\n"
    "precision highp float;\n"
    "\n"
    "varying vec2 v_texCoord; //v2f.texcoord\n"
    "varying vec2 v_blendCoord;\n"
    "uniform sampler2D s_texture0; //_MainTex\n"
    "uniform sampler2D s_blendTexture;\n"
    "uniform vec4 u_baseColor; //v2f.color\n"
    "uniform vec4 u_multiplyColor;\n"
    "uniform vec4 u_screenColor;\n"
    "\n"
    "vec4 ConvertPremultipliedToStraight(vec4 source);\n"
    "vec3 ColorBlend(vec3 colorSource, vec3 colorDestination);\n"
    "vec4 AlphaBlend(vec3 color, vec4 colorSource, vec4 colorDestination);\n"
    "\n"
    "void main()\n"
    "{\n"
    "    vec4 texColor = texture2D(s_texture0, v_texCoord);\n"
    "    texColor.rgb = texColor.rgb * u_multiplyColor.rgb;\n"
    "    texColor.rgb = texColor.rgb + u_screenColor.rgb - (texColor.rgb * u_screenColor.rgb);\n"
    "    vec4 colorSource = texColor * u_baseColor;\n"
    "    vec4 colorDestination = ConvertPremultipliedToStraight(texture2D(s_blendTexture, v_blendCoord));\n"
    "    gl_FragColor = AlphaBlend(ColorBlend(colorSource.rgb, colorDestination.rgb), colorSource, colorDestination);\n"
    "}\n"
    "\n"
    "\n";


// Source: FragShaderSrcBlendTegra.frag
static const char* g_fragShaderSrcBlendTegra =
    "/**\n"
    " * Copyright(c) Live2D Inc. All rights reserved.\n"
    " *\n"
    " * Use of this source code is governed by the Live2D Open Software license\n"
    " * that can be found at https://www.live2d.com/eula/live2d-open-software-license-agreement_en.html.\n"
    " */\n"
    "\n"
    "#version 100\n"
    "#extension GL_NV_shader_framebuffer_fetch : enable\n"
    "\n"
    "precision highp float;\n"
    "\n"
    "varying vec2 v_texCoord; //v2f.texcoord\n"
    "varying vec2 v_blendCoord;\n"
    "uniform sampler2D s_texture0; //_MainTex\n"
    "uniform sampler2D s_blendTexture;\n"
    "uniform vec4 u_baseColor; //v2f.color\n"
    "uniform vec4 u_multiplyColor;\n"
    "uniform vec4 u_screenColor;\n"
    "\n"
    "vec4 ConvertPremultipliedToStraight(vec4 source);\n"
    "vec3 ColorBlend(vec3 colorSource, vec3 colorDestination);\n"
    "vec4 AlphaBlend(vec3 color, vec4 colorSource, vec4 colorDestination);\n"
    "\n"
    "void main()\n"
    "{\n"
    "    vec4 texColor = texture2D(s_texture0, v_texCoord);\n"
    "    texColor.rgb = texColor.rgb * u_multiplyColor.rgb;\n"
    "    texColor.rgb = texColor.rgb + u_screenColor.rgb - (texColor.rgb * u_screenColor.rgb);\n"
    "    vec4 colorSource = texColor * u_baseColor;\n"
    "    vec4 colorDestination = ConvertPremultipliedToStraight(texture2D(s_blendTexture, v_blendCoord));\n"
    "    gl_FragColor = AlphaBlend(ColorBlend(colorSource.rgb, colorDestination.rgb), colorSource, colorDestination);\n"
    "}\n"
    "\n"
    "\n";


// Source: FragShaderSrcColorBlend.frag
static const char* g_fragShaderSrcColorBlend =
    "/**\n"
    " * Copyright(c) Live2D Inc. All rights reserved.\n"
    " *\n"
    " * Use of this source code is governed by the Live2D Open Software license\n"
    " * that can be found at https://www.live2d.com/eula/live2d-open-software-license-agreement_en.html.\n"
    " */\n"
    "\n"
    "vec4 ConvertPremultipliedToStraight(vec4 source)\n"
    "{\n"
    "    if (abs(source.a) < 0.00001)\n"
    "    {\n"
    "        source.rgb = vec3(0.0, 0.0, 0.0);\n"
    "    }\n"
    "    else\n"
    "    {\n"
    "        source.rgb /= source.a;\n"
    "    }\n"
    "\n"
    "    return source;\n"
    "}\n"
    "\n"
    "#if !defined CSM_COLOR_BLEND_MODE\n"
    "#error not define symbol: CSM_COLOR_BLEND_MODE.\n"
    "\n"
    "#elif CSM_COLOR_BLEND_MODE == 0 // NORMAL\n"
    "vec3 ColorBlend(vec3 colorSource, vec3 colorDestination)\n"
    "{\n"
    "    return colorSource;\n"
    "}\n"
    "\n"
    "#elif CSM_COLOR_BLEND_MODE == 1 // ADD\n"
    "vec3 ColorBlend(vec3 colorSource, vec3 colorDestination)\n"
    "{\n"
    "    return min(colorSource + colorDestination, 1.0);\n"
    "}\n"
    "\n"
    "#elif CSM_COLOR_BLEND_MODE == 2 // ADD(GLOW)\n"
    "vec3 ColorBlend(vec3 colorSource, vec3 colorDestination)\n"
    "{\n"
    "    return colorSource + colorDestination;\n"
    "}\n"
    "\n"
    "#elif CSM_COLOR_BLEND_MODE == 3 // DARKEN\n"
    "vec3 ColorBlend(vec3 colorSource, vec3 colorDestination)\n"
    "{\n"
    "    return min(colorSource, colorDestination);\n"
    "}\n"
    "\n"
    "#elif CSM_COLOR_BLEND_MODE == 4 // MULTIPLY\n"
    "vec3 ColorBlend(vec3 colorSource, vec3 colorDestination)\n"
    "{\n"
    "    return colorSource * colorDestination;\n"
    "}\n"
    "\n"
    "#elif CSM_COLOR_BLEND_MODE == 5 // COLOR BURN\n"
    "float ColorBurn(float colorSource, float colorDestination)\n"
    "{\n"
    "    if (abs(colorDestination - 1.0) < 0.000001)\n"
    "    {\n"
    "        return 1.0;\n"
    "    }\n"
    "    else if (abs(colorSource) < 0.000001)\n"
    "    {\n"
    "        return 0.0;\n"
    "    }\n"
    "\n"
    "    return 1.0 - min(1.0, (1.0 - colorDestination) / colorSource);\n"
    "}\n"
    "\n"
    "vec3 ColorBlend(vec3 colorSource, vec3 colorDestination)\n"
    "{\n"
    "    return vec3(\n"
    "        ColorBurn(colorSource.r, colorDestination.r),\n"
    "        ColorBurn(colorSource.g, colorDestination.g),\n"
    "        ColorBurn(colorSource.b, colorDestination.b)\n"
    "    );\n"
    "}\n"
    "\n"
    "#elif CSM_COLOR_BLEND_MODE == 6 // LINEAR BURN\n"
    "vec3 ColorBlend(vec3 colorSource, vec3 colorDestination)\n"
    "{\n"
    "    return max(vec3(0.0), colorSource + colorDestination - 1.0);\n"
    "}\n"
    "\n"
    "#elif CSM_COLOR_BLEND_MODE == 7 // LIGHTEN\n"
    "vec3 ColorBlend(vec3 colorSource, vec3 colorDestination)\n"
    "{\n"
    "    return max(colorSource, colorDestination);\n"
    "}\n"
    "\n"
    "#elif CSM_COLOR_BLEND_MODE == 8 // SCREEN\n"
    "vec3 ColorBlend(vec3 colorSource, vec3 colorDestination)\n"
    "{\n"
    "    return colorSource + colorDestination - colorSource * colorDestination;\n"
    "}\n"
    "\n"
    "#elif CSM_COLOR_BLEND_MODE == 9 // COLOR DODGE\n"
    "float ColorDodge(float colorSource, float colorDestination)\n"
    "{\n"
    "    if (colorDestination <= 0.0)\n"
    "    {\n"
    "        return 0.0;\n"
    "    }\n"
    "    else if (colorSource == 1.0)\n"
    "    {\n"
    "        return 1.0;\n"
    "    }\n"
    "\n"
    "    return min(1.0, colorDestination / (1.0 - colorSource));\n"
    "}\n"
    "\n"
    "vec3 ColorBlend(vec3 colorSource, vec3 colorDestination)\n"
    "{\n"
    "    return vec3(\n"
    "        ColorDodge(colorSource.r, colorDestination.r),\n"
    "        ColorDodge(colorSource.g, colorDestination.g),\n"
    "        ColorDodge(colorSource.b, colorDestination.b)\n"
    "    );\n"
    "}\n"
    "\n"
    "#elif CSM_COLOR_BLEND_MODE == 10 // OVERLAY\n"
    "float Overlay(float colorSource, float colorDestination)\n"
    "{\n"
    "    float mul = 2.0 * colorSource * colorDestination;\n"
    "    float scr = 1.0 - 2.0 * (1.0 - colorSource) * (1.0 - colorDestination) ;\n"
    "    return colorDestination < 0.5 ? mul : scr ;\n"
    "}\n"
    "\n"
    "vec3 ColorBlend(vec3 colorSource, vec3 colorDestination)\n"
    "{\n"
    "    return vec3(\n"
    "        Overlay(colorSource.r, colorDestination.r),\n"
    "        Overlay(colorSource.g, colorDestination.g),\n"
    "        Overlay(colorSource.b, colorDestination.b)\n"
    "    );\n"
    "}\n"
    "\n"
    "#elif CSM_COLOR_BLEND_MODE == 11 // SOFT LIGHT\n"
    "float SoftLight(float colorSource, float colorDestination)\n"
    "{\n"
    "    float val1 = colorDestination - (1.0 - 2.0 * colorSource) * colorDestination * (1.0 - colorDestination);\n"
    "    float val2 = colorDestination + (2.0 * colorSource - 1.0) * colorDestination * ((16.0 * colorDestination - 12.0) * colorDestination + 3.0);\n"
    "    float val3 = colorDestination + (2.0 * colorSource - 1.0) * (sqrt(colorDestination) - colorDestination);\n"
    "\n"
    "    if (colorSource <= 0.5)\n"
    "    {\n"
    "        return val1;\n"
    "    }\n"
    "    else if (colorDestination <= 0.25)\n"
    "    {\n"
    "        return val2;\n"
    "    }\n"
    "\n"
    "    return val3;\n"
    "}\n"
    "\n"
    "vec3 ColorBlend(vec3 colorSource, vec3 colorDestination)\n"
    "{\n"
    "    return vec3(\n"
    "        SoftLight(colorSource.r, colorDestination.r),\n"
    "        SoftLight(colorSource.g, colorDestination.g),\n"
    "        SoftLight(colorSource.b, colorDestination.b)\n"
    "    );\n"
    "}\n"
    "\n"
    "#elif CSM_COLOR_BLEND_MODE == 12 // HARD LIGHT\n"
    "float HardLight(float colorSource, float colorDestination)\n"
    "{\n"
    "    float mul = 2.0 * colorSource * colorDestination;\n"
    "    float scr = 1.0 - 2.0 * (1.0 - colorSource) * (1.0 - colorDestination);\n"
    "\n"
    "    if (colorSource < 0.5)\n"
    "    {\n"
    "        return mul;\n"
    "    }\n"
    "\n"
    "    return scr;\n"
    "}\n"
    "\n"
    "vec3 ColorBlend(vec3 colorSource, vec3 colorDestination)\n"
    "{\n"
    "    return vec3(\n"
    "        HardLight(colorSource.r, colorDestination.r),\n"
    "        HardLight(colorSource.g, colorDestination.g),\n"
    "        HardLight(colorSource.b, colorDestination.b)\n"
    "    );\n"
    "}\n"
    "\n"
    "#elif CSM_COLOR_BLEND_MODE == 13 // LINEAR LIGHT\n"
    "float LinearLight(float colorSource, float colorDestination)\n"
    "{\n"
    "    float burn = max(0.0, 2.0 * colorSource + colorDestination - 1.0);\n"
    "    float dodge = min(1.0, 2.0 * (colorSource - 0.5) + colorDestination);\n"
    "\n"
    "    if (colorSource < 0.5)\n"
    "    {\n"
    "        return burn;\n"
    "    }\n"
    "\n"
    "    return dodge;\n"
    "}\n"
    "\n"
    "vec3 ColorBlend(vec3 colorSource, vec3 colorDestination)\n"
    "{\n"
    "    return vec3(\n"
    "        LinearLight(colorSource.r, colorDestination.r),\n"
    "        LinearLight(colorSource.g, colorDestination.g),\n"
    "        LinearLight(colorSource.b, colorDestination.b)\n"
    "    );\n"
    "}\n"
    "\n"
    "#elif CSM_COLOR_BLEND_MODE == 14 || CSM_COLOR_BLEND_MODE == 15\n"
    "const float rCoeff = 0.30;\n"
    "const float gCoeff = 0.59;\n"
    "const float bCoeff = 0.11;\n"
    "\n"
    "float GetMax(vec3 rgbC)\n"
    "{\n"
    "    return max(rgbC.r, max(rgbC.g, rgbC.b));\n"
    "}\n"
    "\n"
    "float GetMin(vec3 rgbC)\n"
    "{\n"
    "    return min(rgbC.r, min(rgbC.g, rgbC.b));\n"
    "}\n"
    "\n"
    "float GetRange(vec3 rgbC)\n"
    "{\n"
    "    return max(rgbC.r, max(rgbC.g, rgbC.b)) - min(rgbC.r, min(rgbC.g, rgbC.b));\n"
    "}\n"
    "\n"
    "float Saturation(vec3 rgbC)\n"
    "{\n"
    "    return GetRange(rgbC);\n"
    "}\n"
    "\n"
    "float Luma(vec3 rgbC)\n"
    "{\n"
    "    return rCoeff * rgbC.r + gCoeff * rgbC.g + bCoeff * rgbC.b;\n"
    "}\n"
    "\n"
    "vec3 ClipColor(vec3 rgbC)\n"
    "{\n"
    "    float   luma = Luma(rgbC);\n"
    "    float   maxv = GetMax(rgbC);\n"
    "    float   minv = GetMin(rgbC);\n"
    "    vec3    outputColor = rgbC;\n"
    "\n"
    "    outputColor = minv < 0.0 ? luma + (outputColor - luma) * luma / (luma - minv) : outputColor;\n"
    "    outputColor = maxv > 1.0 ? luma + (outputColor - luma) * (1.0 - luma) / (maxv - luma) : outputColor;\n"
    "\n"
    "    return outputColor;\n"
    "}\n"
    "\n"
    "vec3 SetLuma(vec3 rgbC, float luma)\n"
    "{\n"
    "    return ClipColor(rgbC + (luma - Luma(rgbC)));\n"
    "}\n"
    "\n"
    "vec3 SetSaturation(vec3 rgbC, float saturation)\n"
    "{\n"
    "    float maxv = GetMax(rgbC);\n"
    "    float minv = GetMin(rgbC);\n"
    "    float medv = rgbC.r + rgbC.g + rgbC.b - maxv - minv;\n"
    "    float outputMax, outputMed, outputMin;\n"
    "\n"
    "    outputMax = minv < maxv ? saturation : 0.0;\n"
    "    outputMed = minv < maxv ? (medv - minv) * saturation / (maxv - minv) : 0.0;\n"
    "    outputMin = 0.0;\n"
    "\n"
    "    if(rgbC.r == maxv)\n"
    "    {\n"
    "        return rgbC.b < rgbC.g ? vec3(outputMax, outputMed, outputMin) : vec3(outputMax, outputMin, outputMed);\n"
    "    }\n"
    "    else if(rgbC.g == maxv)\n"
    "    {\n"
    "        return rgbC.r < rgbC.b ? vec3(outputMin, outputMax, outputMed) : vec3(outputMed, outputMax, outputMin);\n"
    "    }\n"
    "    else // if(rgbC.b == maxv)\n"
    "    {\n"
    "        return rgbC.g < rgbC.r ? vec3(outputMed, outputMin, outputMax) : vec3(outputMin, outputMed, outputMax);\n"
    "    }\n"
    "}\n"
    "\n"
    "#if CSM_COLOR_BLEND_MODE == 14 // HUE\n"
    "vec3 ColorBlend(vec3 colorSource, vec3 colorDestination)\n"
    "{\n"
    "    return SetLuma(SetSaturation(colorSource, Saturation(colorDestination)), Luma(colorDestination));\n"
    "}\n"
    "\n"
    "#elif CSM_COLOR_BLEND_MODE == 15 // COLOR\n"
    "vec3 ColorBlend(vec3 colorSource, vec3 colorDestination)\n"
    "{\n"
    "    return SetLuma(colorSource, Luma(colorDestination)) ;\n"
    "}\n"
    "\n"
    "#endif\n"
    "\n"
    "#else\n"
    "#error not supported blend function.\n"
    "\n"
    "#endif\n"
    "\n";


// Source: FragShaderSrcCopy.frag
static const char* g_fragShaderSrcCopy =
    "/**\n"
    " * Copyright(c) Live2D Inc. All rights reserved.\n"
    " *\n"
    " * Use of this source code is governed by the Live2D Open Software license\n"
    " * that can be found at https://www.live2d.com/eula/live2d-open-software-license-agreement_en.html.\n"
    " */\n"
    "\n"
    "#version 100\n"
    "\n"
    "precision highp float;\n"
    "\n"
    "varying vec2 v_texCoord;\n"
    "uniform sampler2D s_texture0;\n"
    "uniform vec4 u_baseColor;\n"
    "\n"
    "void main()\n"
    "{\n"
    "    gl_FragColor = texture2D(s_texture0, v_texCoord) * u_baseColor;\n"
    "}\n"
    "\n";


// Source: FragShaderSrcCopyTegra.frag
static const char* g_fragShaderSrcCopyTegra =
    "/**\n"
    " * Copyright(c) Live2D Inc. All rights reserved.\n"
    " *\n"
    " * Use of this source code is governed by the Live2D Open Software license\n"
    " * that can be found at https://www.live2d.com/eula/live2d-open-software-license-agreement_en.html.\n"
    " */\n"
    "\n"
    "#version 100\n"
    "#extension GL_NV_shader_framebuffer_fetch : enable\n"
    "\n"
    "precision highp float;\n"
    "\n"
    "varying vec2 v_texCoord;\n"
    "uniform sampler2D s_texture0;\n"
    "uniform vec4 u_baseColor;\n"
    "\n"
    "void main()\n"
    "{\n"
    "    gl_FragColor = texture2D(s_texture0, v_texCoord) * u_baseColor;\n"
    "}\n"
    "\n";


// Source: FragShaderSrcMask.frag
static const char* g_fragShaderSrcMask =
    "/**\n"
    " * Copyright(c) Live2D Inc. All rights reserved.\n"
    " *\n"
    " * Use of this source code is governed by the Live2D Open Software license\n"
    " * that can be found at https://www.live2d.com/eula/live2d-open-software-license-agreement_en.html.\n"
    " */\n"
    "\n"
    "#version 100\n"
    "\n"
    "precision highp float;\n"
    "\n"
    "varying vec2 v_texCoord;\n"
    "varying vec4 v_clipPos;\n"
    "uniform sampler2D s_texture0;\n"
    "uniform sampler2D s_texture1;\n"
    "uniform vec4 u_channelFlag;\n"
    "uniform vec4 u_baseColor;\n"
    "uniform vec4 u_multiplyColor;\n"
    "uniform vec4 u_screenColor;\n"
    "\n"
    "void main()\n"
    "{\n"
    "    vec4 texColor = texture2D(s_texture0, v_texCoord);\n"
    "    texColor.rgb = texColor.rgb * u_multiplyColor.rgb;\n"
    "    texColor.rgb = texColor.rgb + u_screenColor.rgb - (texColor.rgb * u_screenColor.rgb);\n"
    "    vec4 col_formask = texColor * u_baseColor;\n"
    "    col_formask.rgb = col_formask.rgb  * col_formask.a;\n"
    "    vec4 clipMask = (1.0 - texture2D(s_texture1, v_clipPos.xy / v_clipPos.w)) * u_channelFlag;\n"
    "    float maskVal = clipMask.r + clipMask.g + clipMask.b + clipMask.a;\n"
    "    col_formask = col_formask * maskVal;\n"
    "    gl_FragColor = col_formask;\n"
    "}\n"
    "\n";


// Source: FragShaderSrcMaskBlend.frag
static const char* g_fragShaderSrcMaskBlend =
    "/**\n"
    " * Copyright(c) Live2D Inc. All rights reserved.\n"
    " *\n"
    " * Use of this source code is governed by the Live2D Open Software license\n"
    " * that can be found at https://www.live2d.com/eula/live2d-open-software-license-agreement_en.html.\n"
    " */\n"
    "\n"
    "#version 100\n"
    "\n"
    "precision highp float;\n"
    "\n"
    "varying vec2 v_texCoord;\n"
    "varying vec2 v_blendCoord;\n"
    "varying vec4 v_clipPos;\n"
    "uniform sampler2D s_texture0;\n"
    "uniform sampler2D s_texture1;\n"
    "uniform sampler2D s_blendTexture;\n"
    "uniform vec4 u_channelFlag;\n"
    "uniform vec4 u_baseColor;\n"
    "uniform vec4 u_multiplyColor;\n"
    "uniform vec4 u_screenColor;\n"
    "\n"
    "vec4 ConvertPremultipliedToStraight(vec4 source);\n"
    "vec3 ColorBlend(vec3 colorSource, vec3 colorDestination);\n"
    "vec4 AlphaBlend(vec3 color, vec4 colorSource, vec4 colorDestination);\n"
    "\n"
    "void main()\n"
    "{\n"
    "    vec4 texColor = texture2D(s_texture0, v_texCoord);\n"
    "    texColor.rgb = texColor.rgb * u_multiplyColor.rgb;\n"
    "    texColor.rgb = texColor.rgb + u_screenColor.rgb - (texColor.rgb * u_screenColor.rgb);\n"
    "    vec4 col_formask = texColor * u_baseColor;\n"
    "    vec4 clipMask = (1.0 - texture2D(s_texture1, v_clipPos.xy / v_clipPos.w)) * u_channelFlag;\n"
    "    float maskVal = clipMask.r + clipMask.g + clipMask.b + clipMask.a;\n"
    "    vec4 colorSource = vec4(col_formask.rgb, col_formask.a * maskVal);\n"
    "    vec4 colorDestination = ConvertPremultipliedToStraight(texture2D(s_blendTexture, v_blendCoord));\n"
    "    gl_FragColor = AlphaBlend(ColorBlend(colorSource.rgb, colorDestination.rgb), colorSource, colorDestination);\n"
    "}\n"
    "\n";


// Source: FragShaderSrcMaskBlendTegra.frag
static const char* g_fragShaderSrcMaskBlendTegra =
    "/**\n"
    " * Copyright(c) Live2D Inc. All rights reserved.\n"
    " *\n"
    " * Use of this source code is governed by the Live2D Open Software license\n"
    " * that can be found at https://www.live2d.com/eula/live2d-open-software-license-agreement_en.html.\n"
    " */\n"
    "\n"
    "#version 100\n"
    "#extension GL_NV_shader_framebuffer_fetch : enable\n"
    "\n"
    "precision highp float;\n"
    "\n"
    "varying vec2 v_texCoord;\n"
    "varying vec2 v_blendCoord;\n"
    "varying vec4 v_clipPos;\n"
    "uniform sampler2D s_texture0;\n"
    "uniform sampler2D s_texture1;\n"
    "uniform sampler2D s_blendTexture;\n"
    "uniform vec4 u_channelFlag;\n"
    "uniform vec4 u_baseColor;\n"
    "uniform vec4 u_multiplyColor;\n"
    "uniform vec4 u_screenColor;\n"
    "\n"
    "vec4 ConvertPremultipliedToStraight(vec4 source);\n"
    "vec3 ColorBlend(vec3 colorSource, vec3 colorDestination);\n"
    "vec4 AlphaBlend(vec3 color, vec4 colorSource, vec4 colorDestination);\n"
    "\n"
    "void main()\n"
    "{\n"
    "    vec4 texColor = texture2D(s_texture0, v_texCoord);\n"
    "    texColor.rgb = texColor.rgb * u_multiplyColor.rgb;\n"
    "    texColor.rgb = texColor.rgb + u_screenColor.rgb - (texColor.rgb * u_screenColor.rgb);\n"
    "    vec4 col_formask = texColor * u_baseColor;\n"
    "    vec4 clipMask = (1.0 - texture2D(s_texture1, v_clipPos.xy / v_clipPos.w)) * u_channelFlag;\n"
    "    float maskVal = clipMask.r + clipMask.g + clipMask.b + clipMask.a;\n"
    "    vec4 colorSource = vec4(col_formask.rgb, col_formask.a * maskVal);\n"
    "    vec4 colorDestination = ConvertPremultipliedToStraight(texture2D(s_blendTexture, v_blendCoord));\n"
    "    gl_FragColor = AlphaBlend(ColorBlend(colorSource.rgb, colorDestination.rgb), colorSource, colorDestination);\n"
    "}\n"
    "\n";


// Source: FragShaderSrcMaskInverted.frag
static const char* g_fragShaderSrcMaskInverted =
    "/**\n"
    " * Copyright(c) Live2D Inc. All rights reserved.\n"
    " *\n"
    " * Use of this source code is governed by the Live2D Open Software license\n"
    " * that can be found at https://www.live2d.com/eula/live2d-open-software-license-agreement_en.html.\n"
    " */\n"
    "\n"
    "#version 100\n"
    "\n"
    "precision highp float;\n"
    "\n"
    "varying vec2 v_texCoord;\n"
    "varying vec4 v_clipPos;\n"
    "uniform sampler2D s_texture0;\n"
    "uniform sampler2D s_texture1;\n"
    "uniform vec4 u_channelFlag;\n"
    "uniform vec4 u_baseColor;\n"
    "uniform vec4 u_multiplyColor;\n"
    "uniform vec4 u_screenColor;\n"
    "\n"
    "void main()\n"
    "{\n"
    "    vec4 texColor = texture2D(s_texture0, v_texCoord);\n"
    "    texColor.rgb = texColor.rgb * u_multiplyColor.rgb;\n"
    "    texColor.rgb = texColor.rgb + u_screenColor.rgb - (texColor.rgb * u_screenColor.rgb);\n"
    "    vec4 col_formask = texColor * u_baseColor;\n"
    "    col_formask.rgb = col_formask.rgb  * col_formask.a;\n"
    "    vec4 clipMask = (1.0 - texture2D(s_texture1, v_clipPos.xy / v_clipPos.w)) * u_channelFlag;\n"
    "    float maskVal = clipMask.r + clipMask.g + clipMask.b + clipMask.a;\n"
    "    col_formask = col_formask * (1.0 - maskVal);\n"
    "    gl_FragColor = col_formask;\n"
    "}\n"
    "\n";


// Source: FragShaderSrcMaskInvertedBlend.frag
static const char* g_fragShaderSrcMaskInvertedBlend =
    "/**\n"
    " * Copyright(c) Live2D Inc. All rights reserved.\n"
    " *\n"
    " * Use of this source code is governed by the Live2D Open Software license\n"
    " * that can be found at https://www.live2d.com/eula/live2d-open-software-license-agreement_en.html.\n"
    " */\n"
    "\n"
    "#version 100\n"
    "\n"
    "precision highp float;\n"
    "\n"
    "varying vec2 v_texCoord;\n"
    "varying vec2 v_blendCoord;\n"
    "varying vec4 v_clipPos;\n"
    "uniform sampler2D s_texture0;\n"
    "uniform sampler2D s_texture1;\n"
    "uniform sampler2D s_blendTexture;\n"
    "uniform vec4 u_channelFlag;\n"
    "uniform vec4 u_baseColor;\n"
    "uniform vec4 u_multiplyColor;\n"
    "uniform vec4 u_screenColor;\n"
    "\n"
    "vec4 ConvertPremultipliedToStraight(vec4 source);\n"
    "vec3 ColorBlend(vec3 colorSource, vec3 colorDestination);\n"
    "vec4 AlphaBlend(vec3 color, vec4 colorSource, vec4 colorDestination);\n"
    "\n"
    "void main()\n"
    "{\n"
    "    vec4 texColor = texture2D(s_texture0, v_texCoord);\n"
    "    texColor.rgb = texColor.rgb * u_multiplyColor.rgb;\n"
    "    texColor.rgb = texColor.rgb + u_screenColor.rgb - (texColor.rgb * u_screenColor.rgb);\n"
    "    vec4 col_formask = texColor * u_baseColor;\n"
    "    vec4 clipMask = (1.0 - texture2D(s_texture1, v_clipPos.xy / v_clipPos.w)) * u_channelFlag;\n"
    "    float maskVal = clipMask.r + clipMask.g + clipMask.b + clipMask.a;\n"
    "    vec4 colorSource = vec4(col_formask.rgb, col_formask.a * (1.0 - maskVal));\n"
    "    vec4 colorDestination = ConvertPremultipliedToStraight(texture2D(s_blendTexture, v_blendCoord));\n"
    "    gl_FragColor = AlphaBlend(ColorBlend(colorSource.rgb, colorDestination.rgb), colorSource, colorDestination);\n"
    "}\n"
    "\n";


// Source: FragShaderSrcMaskInvertedBlendTegra.frag
static const char* g_fragShaderSrcMaskInvertedBlendTegra =
    "/**\n"
    " * Copyright(c) Live2D Inc. All rights reserved.\n"
    " *\n"
    " * Use of this source code is governed by the Live2D Open Software license\n"
    " * that can be found at https://www.live2d.com/eula/live2d-open-software-license-agreement_en.html.\n"
    " */\n"
    "\n"
    "#version 100\n"
    "#extension GL_NV_shader_framebuffer_fetch : enable\n"
    "\n"
    "precision highp float;\n"
    "\n"
    "varying vec2 v_texCoord;\n"
    "varying vec2 v_blendCoord;\n"
    "varying vec4 v_clipPos;\n"
    "uniform sampler2D s_texture0;\n"
    "uniform sampler2D s_texture1;\n"
    "uniform sampler2D s_blendTexture;\n"
    "uniform vec4 u_channelFlag;\n"
    "uniform vec4 u_baseColor;\n"
    "uniform vec4 u_multiplyColor;\n"
    "uniform vec4 u_screenColor;\n"
    "\n"
    "vec4 ConvertPremultipliedToStraight(vec4 source);\n"
    "vec3 ColorBlend(vec3 colorSource, vec3 colorDestination);\n"
    "vec4 AlphaBlend(vec3 color, vec4 colorSource, vec4 colorDestination);\n"
    "\n"
    "void main()\n"
    "{\n"
    "    vec4 texColor = texture2D(s_texture0, v_texCoord);\n"
    "    texColor.rgb = texColor.rgb * u_multiplyColor.rgb;\n"
    "    texColor.rgb = texColor.rgb + u_screenColor.rgb - (texColor.rgb * u_screenColor.rgb);\n"
    "    vec4 col_formask = texColor * u_baseColor;\n"
    "    vec4 clipMask = (1.0 - texture2D(s_texture1, v_clipPos.xy / v_clipPos.w)) * u_channelFlag;\n"
    "    float maskVal = clipMask.r + clipMask.g + clipMask.b + clipMask.a;\n"
    "    vec4 colorSource = vec4(col_formask.rgb, col_formask.a * (1.0 - maskVal));\n"
    "    vec4 colorDestination = ConvertPremultipliedToStraight(texture2D(s_blendTexture, v_blendCoord));\n"
    "    gl_FragColor = AlphaBlend(ColorBlend(colorSource.rgb, colorDestination.rgb), colorSource, colorDestination);\n"
    "}\n"
    "\n";


// Source: FragShaderSrcMaskInvertedPremultipliedAlpha.frag
static const char* g_fragShaderSrcMaskInvertedPremultipliedAlpha =
    "/**\n"
    " * Copyright(c) Live2D Inc. All rights reserved.\n"
    " *\n"
    " * Use of this source code is governed by the Live2D Open Software license\n"
    " * that can be found at https://www.live2d.com/eula/live2d-open-software-license-agreement_en.html.\n"
    " */\n"
    "\n"
    "#version 100\n"
    "\n"
    "precision highp float;\n"
    "\n"
    "varying vec2 v_texCoord;\n"
    "varying vec4 v_clipPos;\n"
    "uniform sampler2D s_texture0;\n"
    "uniform sampler2D s_texture1;\n"
    "uniform vec4 u_channelFlag;\n"
    "uniform vec4 u_baseColor;\n"
    "uniform vec4 u_multiplyColor;\n"
    "uniform vec4 u_screenColor;\n"
    "\n"
    "void main()\n"
    "{\n"
    "    vec4 texColor = texture2D(s_texture0, v_texCoord);\n"
    "    texColor.rgb = texColor.rgb * u_multiplyColor.rgb;\n"
    "    texColor.rgb = (texColor.rgb + u_screenColor.rgb * texColor.a) - (texColor.rgb * u_screenColor.rgb);\n"
    "    vec4 col_formask = texColor * u_baseColor;\n"
    "    vec4 clipMask = (1.0 - texture2D(s_texture1, v_clipPos.xy / v_clipPos.w)) * u_channelFlag;\n"
    "    float maskVal = clipMask.r + clipMask.g + clipMask.b + clipMask.a;\n"
    "    col_formask = col_formask * (1.0 - maskVal);\n"
    "    gl_FragColor = col_formask;\n"
    "}\n"
    "\n";


// Source: FragShaderSrcMaskInvertedPremultipliedAlphaBlend.frag
static const char* g_fragShaderSrcMaskInvertedPremultipliedAlphaBlend =
    "/**\n"
    " * Copyright(c) Live2D Inc. All rights reserved.\n"
    " *\n"
    " * Use of this source code is governed by the Live2D Open Software license\n"
    " * that can be found at https://www.live2d.com/eula/live2d-open-software-license-agreement_en.html.\n"
    " */\n"
    "\n"
    "#version 100\n"
    "\n"
    "precision highp float;\n"
    "\n"
    "varying vec2 v_texCoord;\n"
    "varying vec2 v_blendCoord;\n"
    "varying vec4 v_clipPos;\n"
    "uniform sampler2D s_texture0;\n"
    "uniform sampler2D s_texture1;\n"
    "uniform sampler2D s_blendTexture;\n"
    "uniform vec4 u_channelFlag;\n"
    "uniform vec4 u_baseColor;\n"
    "uniform vec4 u_multiplyColor;\n"
    "uniform vec4 u_screenColor;\n"
    "\n"
    "vec4 ConvertPremultipliedToStraight(vec4 source);\n"
    "vec3 ColorBlend(vec3 colorSource, vec3 colorDestination);\n"
    "vec4 AlphaBlend(vec3 color, vec4 colorSource, vec4 colorDestination);\n"
    "\n"
    "void main()\n"
    "{\n"
    "    vec4 texColor = texture2D(s_texture0, v_texCoord);\n"
    "    texColor.rgb = texColor.rgb * u_multiplyColor.rgb;\n"
    "    texColor.rgb = (texColor.rgb + u_screenColor.rgb * texColor.a) - (texColor.rgb * u_screenColor.rgb);\n"
    "    vec4 col_formask = ConvertPremultipliedToStraight(texColor * u_baseColor);\n"
    "    vec4 clipMask = (1.0 - texture2D(s_texture1, v_clipPos.xy / v_clipPos.w)) * u_channelFlag;\n"
    "    float maskVal = clipMask.r + clipMask.g + clipMask.b + clipMask.a;\n"
    "    vec4 colorSource = vec4(col_formask.rgb, col_formask.a * (1.0 - maskVal));\n"
    "    vec4 colorDestination = ConvertPremultipliedToStraight(texture2D(s_blendTexture, v_blendCoord));\n"
    "    gl_FragColor = AlphaBlend(ColorBlend(colorSource.rgb, colorDestination.rgb), colorSource, colorDestination);\n"
    "}\n"
    "\n";


// Source: FragShaderSrcMaskInvertedPremultipliedAlphaBlendTegra.frag
static const char* g_fragShaderSrcMaskInvertedPremultipliedAlphaBlendTegra =
    "/**\n"
    " * Copyright(c) Live2D Inc. All rights reserved.\n"
    " *\n"
    " * Use of this source code is governed by the Live2D Open Software license\n"
    " * that can be found at https://www.live2d.com/eula/live2d-open-software-license-agreement_en.html.\n"
    " */\n"
    "\n"
    "#version 100\n"
    "#extension GL_NV_shader_framebuffer_fetch : enable\n"
    "\n"
    "precision highp float;\n"
    "\n"
    "varying vec2 v_texCoord;\n"
    "varying vec2 v_blendCoord;\n"
    "varying vec4 v_clipPos;\n"
    "uniform sampler2D s_texture0;\n"
    "uniform sampler2D s_texture1;\n"
    "uniform sampler2D s_blendTexture;\n"
    "uniform vec4 u_channelFlag;\n"
    "uniform vec4 u_baseColor;\n"
    "uniform vec4 u_multiplyColor;\n"
    "uniform vec4 u_screenColor;\n"
    "\n"
    "vec4 ConvertPremultipliedToStraight(vec4 source);\n"
    "vec3 ColorBlend(vec3 colorSource, vec3 colorDestination);\n"
    "vec4 AlphaBlend(vec3 color, vec4 colorSource, vec4 colorDestination);\n"
    "\n"
    "void main()\n"
    "{\n"
    "    vec4 texColor = texture2D(s_texture0, v_texCoord);\n"
    "    texColor.rgb = texColor.rgb * u_multiplyColor.rgb;\n"
    "    texColor.rgb = (texColor.rgb + u_screenColor.rgb * texColor.a) - (texColor.rgb * u_screenColor.rgb);\n"
    "    vec4 col_formask = ConvertPremultipliedToStraight(texColor * u_baseColor);\n"
    "    vec4 clipMask = (1.0 - texture2D(s_texture1, v_clipPos.xy / v_clipPos.w)) * u_channelFlag;\n"
    "    float maskVal = clipMask.r + clipMask.g + clipMask.b + clipMask.a;\n"
    "    vec4 colorSource = vec4(col_formask.rgb, col_formask.a * (1.0 - maskVal));\n"
    "    vec4 colorDestination = ConvertPremultipliedToStraight(texture2D(s_blendTexture, v_blendCoord));\n"
    "    gl_FragColor = AlphaBlend(ColorBlend(colorSource.rgb, colorDestination.rgb), colorSource, colorDestination);\n"
    "}\n"
    "\n";


// Source: FragShaderSrcMaskInvertedPremultipliedAlphaTegra.frag
static const char* g_fragShaderSrcMaskInvertedPremultipliedAlphaTegra =
    "/**\n"
    " * Copyright(c) Live2D Inc. All rights reserved.\n"
    " *\n"
    " * Use of this source code is governed by the Live2D Open Software license\n"
    " * that can be found at https://www.live2d.com/eula/live2d-open-software-license-agreement_en.html.\n"
    " */\n"
    "\n"
    "#version 100\n"
    "#extension GL_NV_shader_framebuffer_fetch : enable\n"
    "\n"
    "precision highp float;\n"
    "\n"
    "varying vec2 v_texCoord;\n"
    "varying vec4 v_clipPos;\n"
    "uniform sampler2D s_texture0;\n"
    "uniform sampler2D s_texture1;\n"
    "uniform vec4 u_channelFlag;\n"
    "uniform vec4 u_baseColor;\n"
    "uniform vec4 u_multiplyColor;\n"
    "uniform vec4 u_screenColor;\n"
    "\n"
    "void main()\n"
    "{\n"
    "    vec4 texColor = texture2D(s_texture0, v_texCoord);\n"
    "    texColor.rgb = texColor.rgb * u_multiplyColor.rgb;\n"
    "    texColor.rgb = (texColor.rgb + u_screenColor.rgb * texColor.a) - (texColor.rgb * u_screenColor.rgb);\n"
    "    vec4 col_formask = texColor * u_baseColor;\n"
    "    vec4 clipMask = (1.0 - texture2D(s_texture1, v_clipPos.xy / v_clipPos.w)) * u_channelFlag;\n"
    "    float maskVal = clipMask.r + clipMask.g + clipMask.b + clipMask.a;\n"
    "    col_formask = col_formask * (1.0 - maskVal);\n"
    "    gl_FragColor = col_formask;\n"
    "}\n"
    "\n";


// Source: FragShaderSrcMaskInvertedTegra.frag
static const char* g_fragShaderSrcMaskInvertedTegra =
    "/**\n"
    " * Copyright(c) Live2D Inc. All rights reserved.\n"
    " *\n"
    " * Use of this source code is governed by the Live2D Open Software license\n"
    " * that can be found at https://www.live2d.com/eula/live2d-open-software-license-agreement_en.html.\n"
    " */\n"
    "\n"
    "#version 100\n"
    "#extension GL_NV_shader_framebuffer_fetch : enable\n"
    "\n"
    "precision highp float;\n"
    "\n"
    "varying vec2 v_texCoord;\n"
    "varying vec4 v_clipPos;\n"
    "uniform sampler2D s_texture0;\n"
    "uniform sampler2D s_texture1;\n"
    "uniform vec4 u_channelFlag;\n"
    "uniform vec4 u_baseColor;\n"
    "uniform vec4 u_multiplyColor;\n"
    "uniform vec4 u_screenColor;\n"
    "\n"
    "void main()\n"
    "{\n"
    "    vec4 texColor = texture2D(s_texture0, v_texCoord);\n"
    "    texColor.rgb = texColor.rgb * u_multiplyColor.rgb;\n"
    "    texColor.rgb = texColor.rgb + u_screenColor.rgb - (texColor.rgb * u_screenColor.rgb);\n"
    "    vec4 col_formask = texColor * u_baseColor;\n"
    "    col_formask.rgb = col_formask.rgb  * col_formask.a;\n"
    "    vec4 clipMask = (1.0 - texture2D(s_texture1, v_clipPos.xy / v_clipPos.w)) * u_channelFlag;\n"
    "    float maskVal = clipMask.r + clipMask.g + clipMask.b + clipMask.a;\n"
    "    col_formask = col_formask * (1.0 - maskVal);\n"
    "    gl_FragColor = col_formask;\n"
    "}\n"
    "\n";


// Source: FragShaderSrcMaskPremultipliedAlpha.frag
static const char* g_fragShaderSrcMaskPremultipliedAlpha =
    "/**\n"
    " * Copyright(c) Live2D Inc. All rights reserved.\n"
    " *\n"
    " * Use of this source code is governed by the Live2D Open Software license\n"
    " * that can be found at https://www.live2d.com/eula/live2d-open-software-license-agreement_en.html.\n"
    " */\n"
    "\n"
    "#version 100\n"
    "\n"
    "precision highp float;\n"
    "\n"
    "varying vec2 v_texCoord;\n"
    "varying vec4 v_clipPos;\n"
    "uniform sampler2D s_texture0;\n"
    "uniform sampler2D s_texture1;\n"
    "uniform vec4 u_channelFlag;\n"
    "uniform vec4 u_baseColor;\n"
    "uniform vec4 u_multiplyColor;\n"
    "uniform vec4 u_screenColor;\n"
    "\n"
    "void main()\n"
    "{\n"
    "    vec4 texColor = texture2D(s_texture0, v_texCoord);\n"
    "    texColor.rgb = texColor.rgb * u_multiplyColor.rgb;\n"
    "    texColor.rgb = (texColor.rgb + u_screenColor.rgb * texColor.a) - (texColor.rgb * u_screenColor.rgb);\n"
    "    vec4 col_formask = texColor * u_baseColor;\n"
    "    vec4 clipMask = (1.0 - texture2D(s_texture1, v_clipPos.xy / v_clipPos.w)) * u_channelFlag;\n"
    "    float maskVal = clipMask.r + clipMask.g + clipMask.b + clipMask.a;\n"
    "    col_formask = col_formask * maskVal;\n"
    "    gl_FragColor = col_formask;\n"
    "}\n"
    "\n";


// Source: FragShaderSrcMaskPremultipliedAlphaBlend.frag
static const char* g_fragShaderSrcMaskPremultipliedAlphaBlend =
    "/**\n"
    " * Copyright(c) Live2D Inc. All rights reserved.\n"
    " *\n"
    " * Use of this source code is governed by the Live2D Open Software license\n"
    " * that can be found at https://www.live2d.com/eula/live2d-open-software-license-agreement_en.html.\n"
    " */\n"
    "\n"
    "#version 100\n"
    "\n"
    "precision highp float;\n"
    "\n"
    "varying vec2 v_texCoord;\n"
    "varying vec2 v_blendCoord;\n"
    "varying vec4 v_clipPos;\n"
    "uniform sampler2D s_texture0;\n"
    "uniform sampler2D s_texture1;\n"
    "uniform sampler2D s_blendTexture;\n"
    "uniform vec4 u_channelFlag;\n"
    "uniform vec4 u_baseColor;\n"
    "uniform vec4 u_multiplyColor;\n"
    "uniform vec4 u_screenColor;\n"
    "\n"
    "vec4 ConvertPremultipliedToStraight(vec4 source);\n"
    "vec3 ColorBlend(vec3 colorSource, vec3 colorDestination);\n"
    "vec4 AlphaBlend(vec3 color, vec4 colorSource, vec4 colorDestination);\n"
    "\n"
    "void main()\n"
    "{\n"
    "    vec4 texColor = texture2D(s_texture0, v_texCoord);\n"
    "    texColor.rgb = texColor.rgb * u_multiplyColor.rgb;\n"
    "    texColor.rgb = (texColor.rgb + u_screenColor.rgb * texColor.a) - (texColor.rgb * u_screenColor.rgb);\n"
    "    vec4 col_formask = ConvertPremultipliedToStraight(texColor * u_baseColor);\n"
    "    vec4 clipMask = (1.0 - texture2D(s_texture1, v_clipPos.xy / v_clipPos.w)) * u_channelFlag;\n"
    "    float maskVal = clipMask.r + clipMask.g + clipMask.b + clipMask.a;\n"
    "    vec4 colorSource = vec4(col_formask.rgb, col_formask.a * maskVal);\n"
    "    vec4 colorDestination = ConvertPremultipliedToStraight(texture2D(s_blendTexture, v_blendCoord));\n"
    "    gl_FragColor = AlphaBlend(ColorBlend(colorSource.rgb, colorDestination.rgb), colorSource, colorDestination);\n"
    "}\n"
    "\n";


// Source: FragShaderSrcMaskPremultipliedAlphaBlendTegra.frag
static const char* g_fragShaderSrcMaskPremultipliedAlphaBlendTegra =
    "/**\n"
    " * Copyright(c) Live2D Inc. All rights reserved.\n"
    " *\n"
    " * Use of this source code is governed by the Live2D Open Software license\n"
    " * that can be found at https://www.live2d.com/eula/live2d-open-software-license-agreement_en.html.\n"
    " */\n"
    "\n"
    "#version 100\n"
    "#extension GL_NV_shader_framebuffer_fetch : enable\n"
    "\n"
    "precision highp float;\n"
    "\n"
    "varying vec2 v_texCoord;\n"
    "varying vec2 v_blendCoord;\n"
    "varying vec4 v_clipPos;\n"
    "uniform sampler2D s_texture0;\n"
    "uniform sampler2D s_texture1;\n"
    "uniform sampler2D s_blendTexture;\n"
    "uniform vec4 u_channelFlag;\n"
    "uniform vec4 u_baseColor;\n"
    "uniform vec4 u_multiplyColor;\n"
    "uniform vec4 u_screenColor;\n"
    "\n"
    "vec4 ConvertPremultipliedToStraight(vec4 source);\n"
    "vec3 ColorBlend(vec3 colorSource, vec3 colorDestination);\n"
    "vec4 AlphaBlend(vec3 color, vec4 colorSource, vec4 colorDestination);\n"
    "\n"
    "void main()\n"
    "{\n"
    "    vec4 texColor = texture2D(s_texture0, v_texCoord);\n"
    "    texColor.rgb = texColor.rgb * u_multiplyColor.rgb;\n"
    "    texColor.rgb = (texColor.rgb + u_screenColor.rgb * texColor.a) - (texColor.rgb * u_screenColor.rgb);\n"
    "    vec4 col_formask = ConvertPremultipliedToStraight(texColor * u_baseColor);\n"
    "    vec4 clipMask = (1.0 - texture2D(s_texture1, v_clipPos.xy / v_clipPos.w)) * u_channelFlag;\n"
    "    float maskVal = clipMask.r + clipMask.g + clipMask.b + clipMask.a;\n"
    "    vec4 colorSource = vec4(col_formask.rgb, col_formask.a * maskVal);\n"
    "    vec4 colorDestination = ConvertPremultipliedToStraight(texture2D(s_blendTexture, v_blendCoord));\n"
    "    gl_FragColor = AlphaBlend(ColorBlend(colorSource.rgb, colorDestination.rgb), colorSource, colorDestination);\n"
    "}\n"
    "\n";


// Source: FragShaderSrcMaskPremultipliedAlphaTegra.frag
static const char* g_fragShaderSrcMaskPremultipliedAlphaTegra =
    "/**\n"
    " * Copyright(c) Live2D Inc. All rights reserved.\n"
    " *\n"
    " * Use of this source code is governed by the Live2D Open Software license\n"
    " * that can be found at https://www.live2d.com/eula/live2d-open-software-license-agreement_en.html.\n"
    " */\n"
    "\n"
    "#version 100\n"
    "#extension GL_NV_shader_framebuffer_fetch : enable\n"
    "\n"
    "precision highp float;\n"
    "\n"
    "varying vec2 v_texCoord;\n"
    "varying vec4 v_clipPos;\n"
    "uniform sampler2D s_texture0;\n"
    "uniform sampler2D s_texture1;\n"
    "uniform vec4 u_channelFlag;\n"
    "uniform vec4 u_baseColor;\n"
    "uniform vec4 u_multiplyColor;\n"
    "uniform vec4 u_screenColor;\n"
    "\n"
    "void main()\n"
    "{\n"
    "    vec4 texColor = texture2D(s_texture0, v_texCoord);\n"
    "    texColor.rgb = texColor.rgb * u_multiplyColor.rgb;\n"
    "    texColor.rgb = (texColor.rgb + u_screenColor.rgb * texColor.a) - (texColor.rgb * u_screenColor.rgb);\n"
    "    vec4 col_formask = texColor * u_baseColor;\n"
    "    vec4 clipMask = (1.0 - texture2D(s_texture1, v_clipPos.xy / v_clipPos.w)) * u_channelFlag;\n"
    "    float maskVal = clipMask.r + clipMask.g + clipMask.b + clipMask.a;\n"
    "    col_formask = col_formask * maskVal;\n"
    "    gl_FragColor = col_formask;\n"
    "}\n"
    "\n";


// Source: FragShaderSrcMaskTegra.frag
static const char* g_fragShaderSrcMaskTegra =
    "/**\n"
    " * Copyright(c) Live2D Inc. All rights reserved.\n"
    " *\n"
    " * Use of this source code is governed by the Live2D Open Software license\n"
    " * that can be found at https://www.live2d.com/eula/live2d-open-software-license-agreement_en.html.\n"
    " */\n"
    "\n"
    "#version 100\n"
    "#extension GL_NV_shader_framebuffer_fetch : enable\n"
    "\n"
    "precision highp float;\n"
    "\n"
    "varying vec2 v_texCoord;\n"
    "varying vec4 v_clipPos;\n"
    "uniform sampler2D s_texture0;\n"
    "uniform sampler2D s_texture1;\n"
    "uniform vec4 u_channelFlag;\n"
    "uniform vec4 u_baseColor;\n"
    "uniform vec4 u_multiplyColor;\n"
    "uniform vec4 u_screenColor;\n"
    "\n"
    "void main()\n"
    "{\n"
    "    vec4 texColor = texture2D(s_texture0, v_texCoord);\n"
    "    texColor.rgb = texColor.rgb * u_multiplyColor.rgb;\n"
    "    texColor.rgb = texColor.rgb + u_screenColor.rgb - (texColor.rgb * u_screenColor.rgb);\n"
    "    vec4 col_formask = texColor * u_baseColor;\n"
    "    col_formask.rgb = col_formask.rgb  * col_formask.a;\n"
    "    vec4 clipMask = (1.0 - texture2D(s_texture1, v_clipPos.xy / v_clipPos.w)) * u_channelFlag;\n"
    "    float maskVal = clipMask.r + clipMask.g + clipMask.b + clipMask.a;\n"
    "    col_formask = col_formask * maskVal;\n"
    "    gl_FragColor = col_formask;\n"
    "}\n"
    "\n";


// Source: FragShaderSrcPremultipliedAlpha.frag
static const char* g_fragShaderSrcPremultipliedAlpha =
    "/**\n"
    " * Copyright(c) Live2D Inc. All rights reserved.\n"
    " *\n"
    " * Use of this source code is governed by the Live2D Open Software license\n"
    " * that can be found at https://www.live2d.com/eula/live2d-open-software-license-agreement_en.html.\n"
    " */\n"
    "\n"
    "#version 100\n"
    "\n"
    "precision highp float;\n"
    "\n"
    "varying vec2 v_texCoord; //v2f.texcoord\n"
    "uniform sampler2D s_texture0; //_MainTex\n"
    "uniform vec4 u_baseColor; //v2f.color\n"
    "uniform vec4 u_multiplyColor;\n"
    "uniform vec4 u_screenColor;\n"
    "\n"
    "void main()\n"
    "{\n"
    "    vec4 texColor = texture2D(s_texture0, v_texCoord);\n"
    "    texColor.rgb = texColor.rgb * u_multiplyColor.rgb;\n"
    "    texColor.rgb = (texColor.rgb + u_screenColor.rgb * texColor.a) - (texColor.rgb * u_screenColor.rgb);\n"
    "    gl_FragColor = texColor * u_baseColor;\n"
    "}\n"
    "\n";


// Source: FragShaderSrcPremultipliedAlphaBlend.frag
static const char* g_fragShaderSrcPremultipliedAlphaBlend =
    "/**\n"
    " * Copyright(c) Live2D Inc. All rights reserved.\n"
    " *\n"
    " * Use of this source code is governed by the Live2D Open Software license\n"
    " * that can be found at https://www.live2d.com/eula/live2d-open-software-license-agreement_en.html.\n"
    " */\n"
    "\n"
    "#version 100\n"
    "\n"
    "precision highp float;\n"
    "\n"
    "varying vec2 v_texCoord; //v2f.texcoord\n"
    "varying vec2 v_blendCoord;\n"
    "uniform sampler2D s_texture0; //_MainTex\n"
    "uniform sampler2D s_blendTexture;\n"
    "uniform vec4 u_baseColor; //v2f.color\n"
    "uniform vec4 u_multiplyColor;\n"
    "uniform vec4 u_screenColor;\n"
    "\n"
    "vec4 ConvertPremultipliedToStraight(vec4 source);\n"
    "vec3 ColorBlend(vec3 colorSource, vec3 colorDestination);\n"
    "vec4 AlphaBlend(vec3 color, vec4 colorSource, vec4 colorDestination);\n"
    "\n"
    "void main()\n"
    "{\n"
    "    vec4 texColor = texture2D(s_texture0, v_texCoord);\n"
    "    texColor.rgb = texColor.rgb * u_multiplyColor.rgb;\n"
    "    texColor.rgb = (texColor.rgb + u_screenColor.rgb * texColor.a) - (texColor.rgb * u_screenColor.rgb);\n"
    "    vec4 colorSource = ConvertPremultipliedToStraight(texColor * u_baseColor);\n"
    "    vec4 colorDestination = ConvertPremultipliedToStraight(texture2D(s_blendTexture, v_blendCoord));\n"
    "    gl_FragColor = AlphaBlend(ColorBlend(colorSource.rgb, colorDestination.rgb), colorSource, colorDestination);\n"
    "}\n"
    "\n";


// Source: FragShaderSrcPremultipliedAlphaBlendTegra.frag
static const char* g_fragShaderSrcPremultipliedAlphaBlendTegra =
    "/**\n"
    " * Copyright(c) Live2D Inc. All rights reserved.\n"
    " *\n"
    " * Use of this source code is governed by the Live2D Open Software license\n"
    " * that can be found at https://www.live2d.com/eula/live2d-open-software-license-agreement_en.html.\n"
    " */\n"
    "\n"
    "#version 100\n"
    "#extension GL_NV_shader_framebuffer_fetch : enable\n"
    "\n"
    "precision highp float;\n"
    "\n"
    "varying vec2 v_texCoord; //v2f.texcoord\n"
    "varying vec2 v_blendCoord;\n"
    "uniform sampler2D s_texture0; //_MainTex\n"
    "uniform sampler2D s_blendTexture;\n"
    "uniform vec4 u_baseColor; //v2f.color\n"
    "uniform vec4 u_multiplyColor;\n"
    "uniform vec4 u_screenColor;\n"
    "\n"
    "vec4 ConvertPremultipliedToStraight(vec4 source);\n"
    "vec3 ColorBlend(vec3 colorSource, vec3 colorDestination);\n"
    "vec4 AlphaBlend(vec3 color, vec4 colorSource, vec4 colorDestination);\n"
    "\n"
    "void main()\n"
    "{\n"
    "    vec4 texColor = texture2D(s_texture0, v_texCoord);\n"
    "    texColor.rgb = texColor.rgb * u_multiplyColor.rgb;\n"
    "    texColor.rgb = (texColor.rgb + u_screenColor.rgb * texColor.a) - (texColor.rgb * u_screenColor.rgb);\n"
    "    vec4 colorSource = ConvertPremultipliedToStraight(texColor * u_baseColor);\n"
    "    vec4 colorDestination = ConvertPremultipliedToStraight(texture2D(s_blendTexture, v_blendCoord));\n"
    "    gl_FragColor = AlphaBlend(ColorBlend(colorSource.rgb, colorDestination.rgb), colorSource, colorDestination);\n"
    "}\n"
    "\n";


// Source: FragShaderSrcPremultipliedAlphaTegra.frag
static const char* g_fragShaderSrcPremultipliedAlphaTegra =
    "/**\n"
    " * Copyright(c) Live2D Inc. All rights reserved.\n"
    " *\n"
    " * Use of this source code is governed by the Live2D Open Software license\n"
    " * that can be found at https://www.live2d.com/eula/live2d-open-software-license-agreement_en.html.\n"
    " */\n"
    "\n"
    "#version 100\n"
    "#extension GL_NV_shader_framebuffer_fetch : enable\n"
    "\n"
    "precision highp float;\n"
    "\n"
    "varying vec2 v_texCoord; //v2f.texcoord\n"
    "uniform sampler2D s_texture0; //_MainTex\n"
    "uniform vec4 u_baseColor; //v2f.color\n"
    "uniform vec4 u_multiplyColor;\n"
    "uniform vec4 u_screenColor;\n"
    "\n"
    "void main()\n"
    "{\n"
    "    vec4 texColor = texture2D(s_texture0, v_texCoord);\n"
    "    texColor.rgb = texColor.rgb * u_multiplyColor.rgb;\n"
    "    texColor.rgb = (texColor.rgb + u_screenColor.rgb * texColor.a) - (texColor.rgb * u_screenColor.rgb);\n"
    "    gl_FragColor = texColor * u_baseColor;\n"
    "}\n"
    "\n";


// Source: FragShaderSrcSetupMask.frag
static const char* g_fragShaderSrcSetupMask =
    "/**\n"
    " * Copyright(c) Live2D Inc. All rights reserved.\n"
    " *\n"
    " * Use of this source code is governed by the Live2D Open Software license\n"
    " * that can be found at https://www.live2d.com/eula/live2d-open-software-license-agreement_en.html.\n"
    " */\n"
    "\n"
    "#version 100\n"
    "\n"
    "precision highp float;\n"
    "\n"
    "varying vec2 v_texCoord;\n"
    "varying vec4 v_myPos;\n"
    "uniform sampler2D s_texture0;\n"
    "uniform vec4 u_channelFlag;\n"
    "uniform vec4 u_baseColor;\n"
    "\n"
    "void main()\n"
    "{\n"
    "    float isInside =\n"
    "        step(u_baseColor.x, v_myPos.x/v_myPos.w)\n"
    "        * step(u_baseColor.y, v_myPos.y/v_myPos.w)\n"
    "        * step(v_myPos.x/v_myPos.w, u_baseColor.z)\n"
    "        * step(v_myPos.y/v_myPos.w, u_baseColor.w);\n"
    "\n"
    "    gl_FragColor = u_channelFlag * texture2D(s_texture0, v_texCoord).a * isInside;\n"
    "}\n"
    "\n";


// Source: FragShaderSrcSetupMaskTegra.frag
static const char* g_fragShaderSrcSetupMaskTegra =
    "/**\n"
    " * Copyright(c) Live2D Inc. All rights reserved.\n"
    " *\n"
    " * Use of this source code is governed by the Live2D Open Software license\n"
    " * that can be found at https://www.live2d.com/eula/live2d-open-software-license-agreement_en.html.\n"
    " */\n"
    "\n"
    "#version 100\n"
    "#extension GL_NV_shader_framebuffer_fetch : enable\n"
    "\n"
    "precision highp float;\n"
    "\n"
    "varying vec2 v_texCoord;\n"
    "varying vec4 v_myPos;\n"
    "uniform sampler2D s_texture0;\n"
    "uniform vec4 u_channelFlag;\n"
    "uniform vec4 u_baseColor;\n"
    "\n"
    "void main()\n"
    "{\n"
    "    float isInside =\n"
    "        step(u_baseColor.x, v_myPos.x/v_myPos.w)\n"
    "        * step(u_baseColor.y, v_myPos.y/v_myPos.w)\n"
    "        * step(v_myPos.x/v_myPos.w, u_baseColor.z)\n"
    "        * step(v_myPos.y/v_myPos.w, u_baseColor.w);\n"
    "\n"
    "    gl_FragColor = u_channelFlag * texture2D(s_texture0, v_texCoord).a * isInside;\n"
    "}\n"
    "\n";


// Source: FragShaderSrcTegra.frag
static const char* g_fragShaderSrcTegra =
    "/**\n"
    " * Copyright(c) Live2D Inc. All rights reserved.\n"
    " *\n"
    " * Use of this source code is governed by the Live2D Open Software license\n"
    " * that can be found at https://www.live2d.com/eula/live2d-open-software-license-agreement_en.html.\n"
    " */\n"
    "\n"
    "#version 100\n"
    "#extension GL_NV_shader_framebuffer_fetch : enable\n"
    "\n"
    "precision highp float;\n"
    "\n"
    "varying vec2 v_texCoord; //v2f.texcoord\n"
    "uniform sampler2D s_texture0; //_MainTex\n"
    "uniform vec4 u_baseColor; //v2f.color\n"
    "uniform vec4 u_multiplyColor;\n"
    "uniform vec4 u_screenColor;\n"
    "\n"
    "void main()\n"
    "{\n"
    "    vec4 texColor = texture2D(s_texture0, v_texCoord);\n"
    "    texColor.rgb = texColor.rgb * u_multiplyColor.rgb;\n"
    "    texColor.rgb = texColor.rgb + u_screenColor.rgb - (texColor.rgb * u_screenColor.rgb);\n"
    "    vec4 color = texColor * u_baseColor;\n"
    "    gl_FragColor = vec4(color.rgb * color.a, color.a);\n"
    "}\n"
    "\n";


// Source: VertShaderSrc.vert
static const char* g_vertShaderSrc =
    "/**\n"
    " * Copyright(c) Live2D Inc. All rights reserved.\n"
    " *\n"
    " * Use of this source code is governed by the Live2D Open Software license\n"
    " * that can be found at https://www.live2d.com/eula/live2d-open-software-license-agreement_en.html.\n"
    " */\n"
    "\n"
    "#version 100\n"
    "\n"
    "attribute vec4 a_position; //v.vertex\n"
    "attribute vec2 a_texCoord; //v.texcoord\n"
    "varying vec2 v_texCoord; //v2f.texcoord\n"
    "uniform mat4 u_matrix;\n"
    "\n"
    "void main()\n"
    "{\n"
    "    gl_Position = u_matrix * a_position;\n"
    "    v_texCoord = a_texCoord;\n"
    "    v_texCoord.y = 1.0 - v_texCoord.y;\n"
    "}\n"
    "\n";


// Source: VertShaderSrcBlend.vert
static const char* g_vertShaderSrcBlend =
    "/**\n"
    " * Copyright(c) Live2D Inc. All rights reserved.\n"
    " *\n"
    " * Use of this source code is governed by the Live2D Open Software license\n"
    " * that can be found at https://www.live2d.com/eula/live2d-open-software-license-agreement_en.html.\n"
    " */\n"
    "\n"
    "#version 100\n"
    "\n"
    "attribute vec4 a_position; //v.vertex\n"
    "attribute vec2 a_texCoord; //v.texcoord\n"
    "varying vec2 v_texCoord; //v2f.texcoord\n"
    "varying vec2 v_blendCoord;\n"
    "uniform mat4 u_matrix;\n"
    "\n"
    "void main()\n"
    "{\n"
    "    gl_Position = u_matrix * a_position;\n"
    "    v_texCoord = a_texCoord;\n"
    "    v_texCoord.y = 1.0 - v_texCoord.y;\n"
    "    vec2 ndcPos = gl_Position.xy / gl_Position.w;\n"
    "    v_blendCoord = ndcPos * 0.5 + 0.5;\n"
    "}\n"
    "\n";


// Source: VertShaderSrcCopy.vert
static const char* g_vertShaderSrcCopy =
    "/**\n"
    " * Copyright(c) Live2D Inc. All rights reserved.\n"
    " *\n"
    " * Use of this source code is governed by the Live2D Open Software license\n"
    " * that can be found at https://www.live2d.com/eula/live2d-open-software-license-agreement_en.html.\n"
    " */\n"
    "\n"
    "#version 100\n"
    "\n"
    "attribute vec4 a_position;\n"
    "attribute vec2 a_texCoord;\n"
    "varying vec2 v_texCoord;\n"
    "\n"
    "void main()\n"
    "{\n"
    "    v_texCoord = a_texCoord;\n"
    "    gl_Position = a_position;\n"
    "}\n"
    "\n";


// Source: VertShaderSrcMasked.vert
static const char* g_vertShaderSrcMasked =
    "/**\n"
    " * Copyright(c) Live2D Inc. All rights reserved.\n"
    " *\n"
    " * Use of this source code is governed by the Live2D Open Software license\n"
    " * that can be found at https://www.live2d.com/eula/live2d-open-software-license-agreement_en.html.\n"
    " */\n"
    "\n"
    "#version 100\n"
    "\n"
    "attribute vec4 a_position;\n"
    "attribute vec2 a_texCoord;\n"
    "varying vec2 v_texCoord;\n"
    "varying vec4 v_clipPos;\n"
    "uniform mat4 u_matrix;\n"
    "uniform mat4 u_clipMatrix;\n"
    "\n"
    "void main()\n"
    "{\n"
    "    gl_Position = u_matrix * a_position;\n"
    "    v_clipPos = u_clipMatrix * a_position;\n"
    "    v_texCoord = a_texCoord;\n"
    "    v_texCoord.y = 1.0 - v_texCoord.y;\n"
    "}\n"
    "\n";


// Source: VertShaderSrcMaskedBlend.vert
static const char* g_vertShaderSrcMaskedBlend =
    "/**\n"
    " * Copyright(c) Live2D Inc. All rights reserved.\n"
    " *\n"
    " * Use of this source code is governed by the Live2D Open Software license\n"
    " * that can be found at https://www.live2d.com/eula/live2d-open-software-license-agreement_en.html.\n"
    " */\n"
    "\n"
    "#version 100\n"
    "\n"
    "attribute vec4 a_position;\n"
    "attribute vec2 a_texCoord;\n"
    "varying vec2 v_texCoord;\n"
    "varying vec2 v_blendCoord;\n"
    "varying vec4 v_clipPos;\n"
    "uniform mat4 u_matrix;\n"
    "uniform mat4 u_clipMatrix;\n"
    "\n"
    "void main()\n"
    "{\n"
    "    gl_Position = u_matrix * a_position;\n"
    "    v_clipPos = u_clipMatrix * a_position;\n"
    "    v_texCoord = a_texCoord;\n"
    "    v_texCoord.y = 1.0 - v_texCoord.y;\n"
    "    vec2 ndcPos = gl_Position.xy / gl_Position.w;\n"
    "    v_blendCoord = ndcPos * 0.5 + 0.5;\n"
    "}\n"
    "\n";


// Source: VertShaderSrcSetupMask.vert
static const char* g_vertShaderSrcSetupMask =
    "/**\n"
    " * Copyright(c) Live2D Inc. All rights reserved.\n"
    " *\n"
    " * Use of this source code is governed by the Live2D Open Software license\n"
    " * that can be found at https://www.live2d.com/eula/live2d-open-software-license-agreement_en.html.\n"
    " */\n"
    "\n"
    "#version 100\n"
    "\n"
    "attribute vec4 a_position;\n"
    "attribute vec2 a_texCoord;\n"
    "varying vec2 v_texCoord;\n"
    "varying vec4 v_myPos;\n"
    "uniform mat4 u_clipMatrix;\n"
    "\n"
    "void main()\n"
    "{\n"
    "    gl_Position = u_clipMatrix * a_position;\n"
    "    v_myPos = u_clipMatrix * a_position;\n"
    "    v_texCoord = a_texCoord;\n"
    "    v_texCoord.y = 1.0 - v_texCoord.y;\n"
    "}\n"
    "\n";


// ============================================================
// Sprite Shaders (CubismNativeSamples / StandardES)
// ============================================================

// Source: FragSprite.frag
static const char* g_fragSprite =
    "/**\n"
    " * Copyright(c) Live2D Inc. All rights reserved.\n"
    " *\n"
    " * Use of this source code is governed by the Live2D Open Software license\n"
    " * that can be found at https://www.live2d.com/eula/live2d-open-software-license-agreement_en.html.\n"
    " */\n"
    "\n"
    "#version 100\n"
    "\n"
    "precision mediump float;\n"
    "\n"
    "varying vec2 vuv;\n"
    "uniform sampler2D texture;\n"
    "uniform vec4 baseColor;\n"
    "\n"
    "void main(void)\n"
    "{\n"
    "    gl_FragColor = texture2D(texture, vuv) * baseColor;\n"
    "}\n"
    "\n";


// Source: VertSprite.vert
static const char* g_vertSprite =
    "/**\n"
    " * Copyright(c) Live2D Inc. All rights reserved.\n"
    " *\n"
    " * Use of this source code is governed by the Live2D Open Software license\n"
    " * that can be found at https://www.live2d.com/eula/live2d-open-software-license-agreement_en.html.\n"
    " */\n"
    "\n"
    "#version 100\n"
    "\n"
    "attribute vec3 position;\n"
    "attribute vec2 uv;\n"
    "varying vec2 vuv;\n"
    "\n"
    "void main(void)\n"
    "{\n"
    "    gl_Position = vec4(position, 1.0);\n"
    "    vuv = uv;\n"
    "}\n"
    "\n";


// ============================================================
// Shader Lookup
// ============================================================

struct ShaderEntry {
    const char* name;
    const char* source;
};

static const ShaderEntry g_shaderTable[] = {
    { "FragShaderSrc.frag", g_fragShaderSrc },
    { "FragShaderSrcAlphaBlend.frag", g_fragShaderSrcAlphaBlend },
    { "FragShaderSrcBlend.frag", g_fragShaderSrcBlend },
    { "FragShaderSrcBlendTegra.frag", g_fragShaderSrcBlendTegra },
    { "FragShaderSrcColorBlend.frag", g_fragShaderSrcColorBlend },
    { "FragShaderSrcCopy.frag", g_fragShaderSrcCopy },
    { "FragShaderSrcCopyTegra.frag", g_fragShaderSrcCopyTegra },
    { "FragShaderSrcMask.frag", g_fragShaderSrcMask },
    { "FragShaderSrcMaskBlend.frag", g_fragShaderSrcMaskBlend },
    { "FragShaderSrcMaskBlendTegra.frag", g_fragShaderSrcMaskBlendTegra },
    { "FragShaderSrcMaskInverted.frag", g_fragShaderSrcMaskInverted },
    { "FragShaderSrcMaskInvertedBlend.frag", g_fragShaderSrcMaskInvertedBlend },
    { "FragShaderSrcMaskInvertedBlendTegra.frag", g_fragShaderSrcMaskInvertedBlendTegra },
    { "FragShaderSrcMaskInvertedPremultipliedAlpha.frag", g_fragShaderSrcMaskInvertedPremultipliedAlpha },
    { "FragShaderSrcMaskInvertedPremultipliedAlphaBlend.frag", g_fragShaderSrcMaskInvertedPremultipliedAlphaBlend },
    { "FragShaderSrcMaskInvertedPremultipliedAlphaBlendTegra.frag", g_fragShaderSrcMaskInvertedPremultipliedAlphaBlendTegra },
    { "FragShaderSrcMaskInvertedPremultipliedAlphaTegra.frag", g_fragShaderSrcMaskInvertedPremultipliedAlphaTegra },
    { "FragShaderSrcMaskInvertedTegra.frag", g_fragShaderSrcMaskInvertedTegra },
    { "FragShaderSrcMaskPremultipliedAlpha.frag", g_fragShaderSrcMaskPremultipliedAlpha },
    { "FragShaderSrcMaskPremultipliedAlphaBlend.frag", g_fragShaderSrcMaskPremultipliedAlphaBlend },
    { "FragShaderSrcMaskPremultipliedAlphaBlendTegra.frag", g_fragShaderSrcMaskPremultipliedAlphaBlendTegra },
    { "FragShaderSrcMaskPremultipliedAlphaTegra.frag", g_fragShaderSrcMaskPremultipliedAlphaTegra },
    { "FragShaderSrcMaskTegra.frag", g_fragShaderSrcMaskTegra },
    { "FragShaderSrcPremultipliedAlpha.frag", g_fragShaderSrcPremultipliedAlpha },
    { "FragShaderSrcPremultipliedAlphaBlend.frag", g_fragShaderSrcPremultipliedAlphaBlend },
    { "FragShaderSrcPremultipliedAlphaBlendTegra.frag", g_fragShaderSrcPremultipliedAlphaBlendTegra },
    { "FragShaderSrcPremultipliedAlphaTegra.frag", g_fragShaderSrcPremultipliedAlphaTegra },
    { "FragShaderSrcSetupMask.frag", g_fragShaderSrcSetupMask },
    { "FragShaderSrcSetupMaskTegra.frag", g_fragShaderSrcSetupMaskTegra },
    { "FragShaderSrcTegra.frag", g_fragShaderSrcTegra },
    { "VertShaderSrc.vert", g_vertShaderSrc },
    { "VertShaderSrcBlend.vert", g_vertShaderSrcBlend },
    { "VertShaderSrcCopy.vert", g_vertShaderSrcCopy },
    { "VertShaderSrcMasked.vert", g_vertShaderSrcMasked },
    { "VertShaderSrcMaskedBlend.vert", g_vertShaderSrcMaskedBlend },
    { "VertShaderSrcSetupMask.vert", g_vertShaderSrcSetupMask },
    { "FragSprite.frag", g_fragSprite },
    { "VertSprite.vert", g_vertSprite },
};

static const int g_shaderCount = 38;

/**
 * Look up a shader source by filename.
 * Handles both bare names (e.g. "VertShaderSrc.vert") and
 * prefixed names (e.g. "FrameworkShaders/VertShaderSrc.vert").
 * Returns nullptr if not found.
 */
static const char* FindShaderByName(const char* name)
{
    if (!name) return nullptr;

    // If the name contains a path separator, skip to the basename.
    const char* basename = name;
    const char* slash = strrchr(name, '/');
    if (slash) {
        basename = slash + 1;
    }

    for (int i = 0; i < g_shaderCount; ++i) {
        if (strcmp(g_shaderTable[i].name, basename) == 0) {
            return g_shaderTable[i].source;
        }
    }
    return nullptr;
}
